# Generated by Django 3.0.4 on 2020-03-23 16:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import mediahub.validators


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.CharField(max_length=255, null=True)),
                ('url', models.CharField(max_length=700, null=True)),
                ('icon', models.CharField(max_length=255)),
                ('widgetColor', models.CharField(max_length=255)),
                ('view', models.CharField(blank=True, max_length=255, null=True)),
                ('sortOrder', models.IntegerField()),
                ('createdOn', models.DateTimeField(auto_now_add=True)),
                ('creeatedBy', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('headline', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('slug', models.SlugField(blank=True, max_length=100, null=True)),
                ('tags', models.CharField(blank=True, max_length=255, null=True)),
                ('createdOn', models.DateTimeField(auto_now_add=True)),
                ('updatedOn', models.DateTimeField(auto_now_add=True)),
                ('upload', models.FileField(blank=True, null=True, upload_to='%Y/%m/%d/', validators=[mediahub.validators.validate_file_extension])),
                ('thumb', models.CharField(blank=True, default='media/thumbs/default.png', max_length=255)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mediahub.Category')),
                ('createdBy', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='post_requests_created', to=settings.AUTH_USER_MODEL)),
                ('updatedBy', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='post_requests_updated', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
