# Generated by Django 3.0.4 on 2020-03-23 16:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mediahub', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='view',
        ),
    ]
